services:
  postgres:
    image: postgres:16
    container_name: sistema-acessos-postgres
    environment:
      POSTGRES_DB: sistema_acessos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sistema_acessos_postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-acessos-auth-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sistema_acessos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"

volumes:
  sistema_acessos_postgres_data: